#!/bin/sh
saveTo=/root/mikrotik
now=$(date);

echo "# Generated by Dev4you.lt on $now" > $saveTo/dshield.rsc
echo "/ip firewall address-list" >> $saveTo/dshield.rsc
wget -q -O - http://feeds.dshield.org/block.txt | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.0\t/ { print "add list=00_dshield address=" $1 "/24 comment=dshield";}' >> $saveTo/dshield.rsc


