#!/bin/bash
# Descarga de URLs blacklisteadas
# Spamhaus DROP list (Don't Route Or Peer Lists)

wget https://www.spamhaus.org/drop/drop.txt &&

mv drop.txt spamhausDROPlst &&

sed -i.bak '/^;/d' ./spamhausDROPlst &&

sed -i.bak 's/ ; .*$/ ; /g' ./spamhausDROPlst &&

awk '{ printf "add list=blacklist comment=blacklist address="; print }' spamhausDROPlst > spamhausDROPlst.000 &&

echo "/ip firewall address-list" > tmp.txt && cat tmp.txt spamhausDROPlst.000 > spamhausDROPlst.rsc &&

sed -i.bak 's/ ; //g' spamhausDROPlst.rsc &&

rm spamhausDROPlst spamhausDROPlst.000 tmp.txt *.bak
