#!/bin/sh
saveTo=/root/mikrotik
now=$(date);
echo "# Generated by Dev4you.lt on $now" > $saveTo/firehol_level1.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level1.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level1.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level1 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level1.rsc
echo "1 OK"
echo "# Generated by Dev4you.lt on $now" > $saveTo/firehol_level2.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level2.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level2.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level2 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level2.rsc
echo "2 OK\n"
echo "# Generated by Dev4you.lt on $now" > $saveTo/firehol_level3.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level3.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level3.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level3 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level3.rsc
echo "3 OK\n"
echo "# Generated by Dev4you.lt on $now" > $saveTo/firehol_level4.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level4.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level4.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level4 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level4.rsc
echo "4 OK\n"
echo "# Generated by Dev4you.lt on $now" > $saveTo/firehol_webserver.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_webserver.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_webserver.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_webserver address=" $1 " comment=firehol_webserver";}' >> $saveTo/firehol_webserver.rsc
echo "5 OK\n"
echo "# Generated by Dev4you.lt on $now" > $saveTo/firehol_webclient.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_malware.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_webclient.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_malware address=" $1 " comment=firehol_malware";}' >> $saveTo/firehol_malware.rsc
echo "6 OK\n"
echo "# Generated by Dev4you.lt on $now" > $saveTo/firehol_abusers_1d.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_abusers_1d.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_abusers_1d.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_abusers_1d address=" $1 " comment=firehol_abusers_1d";}' >> $saveTo/firehol_abusers_1d.rsc
echo "7 OK\n"
echo "# Generated by Dev4you.lt on $now" > $saveTo/firehol_abusers_30d.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_abusers_30d.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_abusers_30d.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_abusers_30d address=" $1 " comment=firehol_abusers_30d";}' >> $saveTo/firehol_abusers_30d.rsc
echo "8 OK\n"
echo "# Generated by Dev4you.lt on $now" > $saveTo/bruteforceblocker.rsc
echo "/ip firewall address-list" >> $saveTo/bruteforceblocker.rsc
wget -q -O - http://danger.rulez.sk/projects/bruteforceblocker/blist.php | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_bruteforceblocker address=" $1 " comment=bruteforceblocker";}' >> $saveTo/bruteforceblocker.rsc
echo "9 OK\n"
echo "# Generated by Dev4you.lt on $now" > $saveTo/dshield.rsc
echo "/ip firewall address-list" >> $saveTo/dshield.rsc
wget -q -O - http://feeds.dshield.org/block.txt | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.0\t/ { print "add list=00_dshield address=" $1 "/24 comment=dshield";}' >> $saveTo/dshield.rsc
echo "10 OK\n"
echo "# Generated by Dev4you.lt on $now" > $saveTo/drop.rsc
echo "/ip firewall address-list" >> $saveTo/drop.rsc
wget -q -O - http://www.spamhaus.org/drop/drop.txt | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\// { print "add list=00_drop address=" $1 "/24 comment=spamhaus-drop";}' >> $saveTo/drop.rsc
echo "11 OK\n"
echo "# Generated by Dev4you.lt on $now" > $saveTo/edrop.rsc
echo "/ip firewall address-list" >> $saveTo/edrop.rsc
wget -q -O - http://www.spamhaus.org/drop/edrop.txt | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\// { print "add list=00_edrop address=" $1 "/24 comment=spamhaus-edrop";}' >> $saveTo/edrop.rsc
echo "12 OK\n"


echo "THE END OK\n"